spring:
  application: sistema-cadastro-api
  datasource:
    url: jdbc:mysql://localhost:3306/sistema_cadastro?useTimezone=true&serverTimeZone=UTC
    username: root
    password: admin


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true


server:
  port: 9090
